=== SasZombie/WebLogistics/server/content/xml/users.dtd
<!ELEMENT users (user+)>
<!ATTLIST users xmlns:xsi CDATA #IMPLIED>
<!ATTLIST users xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT user (name, surrname, preferedTheme, readingLvl)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surrname (#PCDATA)>
<!ELEMENT preferedTheme (#PCDATA)>
<!ELEMENT readingLvl (#PCDATA)>

=== SasZombie/WebLogistics/server/content/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE users SYSTEM "users.dtd">
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <user>
    <name>Sas</name>
    <surrname>Zombie</surrname>
    <preferedTheme>Magic</preferedTheme>
    <readingLvl>Intermediate</readingLvl>
  </user>
    <user>
        <name>Salut</name>
        <surrname>Sas</surrname>
        <preferedTheme>Magic</preferedTheme>
        <readingLvl>Beginer</readingLvl>
    </user>
</users>
