=== SasZombie/WebLogistics/public/xml/books.dtd
<!ELEMENT books (book*)>
<!ATTLIST books xmlns:xsi CDATA #IMPLIED>
<!ATTLIST books xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT book (title, theme1, theme2, readingLvl)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT theme1 (#PCDATA)>
<!ELEMENT theme2 (#PCDATA)>
<!ELEMENT readingLvl (#PCDATA)>

=== SasZombie/WebLogistics/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <title>
            TitluTest
        </title>
        <theme1>
            Fantesy
        </theme1>
        <theme2>
            Mystery
        </theme2>
        <readingLvl>
            Intermediate
        </readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>Ttt</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>asdasd</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Intermediate</readingLvl>
    </book>
    <book>
        <title>ASDsad</title>
        <theme1>123</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>asdsda</title>
        <theme1>123213</theme1>
        <theme2>123123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>123</title>
        <theme1>123123</theme1>
        <theme2>123312</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>123213</title>
        <theme1>asdasd</theme1>
        <theme2>asdsad</theme2>
        <readingLvl>Intermediate</readingLvl>
    </book>
    <book>
        <title>Salut</title>
        <theme1>asd</theme1>
        <theme2>213</theme2>
        <readingLvl></readingLvl>
    </book>
    <book>
        <title>Salut</title>
        <theme1>asd</theme1>
        <theme2>213</theme2>
        <readingLvl></readingLvl>
    </book>
    <book>
        <title>Salut</title>
        <theme1>asd</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>undefined</title>
        <theme1>undefined</theme1>
        <theme2>undefined</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
    <book>
        <title>asddsa</title>
        <theme1>asdasd</theme1>
        <theme2>123</theme2>
        <readingLvl>Beginer</readingLvl>
    </book>
</books>

=== SasZombie/WebLogistics/public/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <title>1984 (Signet Classics)</title>
        <theme1>Magic</theme1>
        <theme2>Fantesy</theme2>
        <readingLvl>Intermediate</readingLvl>
    </book>
    <book>
        <title>Adventures of Huckleberry Finn</title>
        <theme1>Magic</theme1>
        <theme2>Real</theme2>
        <readingLvl>Beginner</readingLvl>
    </book>
</books>
